# Generated by Django 3.2.5 on 2022-10-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_active', models.BooleanField(default=True, verbose_name='تنشيط المصانع')),
                ('product_active', models.BooleanField(default=True, verbose_name='تنشيط المنتجات')),
                ('seller_active', models.BooleanField(default=True, verbose_name='تنشيط التجار')),
                ('worker_active', models.BooleanField(default=True, verbose_name='تنشيط العمال ')),
                ('invoice_active', models.BooleanField(default=True, verbose_name='تنشيط الفواتير ')),
                ('supplier_active', models.BooleanField(default=True, verbose_name='تنشيط الموردين ')),
            ],
        ),
        migrations.CreateModel(
            name='SystemInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='شعارالنظام')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='اسم النظام')),
                ('type', models.CharField(max_length=50, null=True, verbose_name='نوع النظام')),
                ('manage', models.CharField(max_length=50, null=True, verbose_name='إدارة')),
                ('phone', models.CharField(max_length=11, null=True, verbose_name='هاتف 1')),
                ('phone2', models.CharField(blank=True, max_length=11, null=True, verbose_name='هاتف 2')),
                ('address', models.CharField(max_length=150, null=True, verbose_name='العنوان')),
                ('geo_site', models.CharField(blank=True, max_length=150, null=True, verbose_name='موقعك الجغرافي')),
            ],
        ),
    ]
