# Generated by Django 3.2.5 on 2022-10-03 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='supplier_loads_active',
            field=models.BooleanField(default=True, verbose_name='تنشيط التوريد'),
        ),
    ]
