# Generated by Django 3.2.5 on 2022-12-04 14:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الشركة')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='رقم الهاتف')),
                ('active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GeoPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الموقع')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='رقم الهاتف')),
                ('price', models.FloatField(default=0.0, verbose_name='سعر الموقع')),
                ('material_price', models.FloatField(default=0.0, verbose_name='سعر الخامة')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.company', verbose_name='الشركة المسؤولة')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المورد')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='رقم الهاتف')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('cash_amount', models.FloatField(default=0, null=True, verbose_name='القيمة النقدية')),
                ('desc', models.CharField(max_length=250, null=True, verbose_name='الوصف/السبب')),
                ('payment_date', models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.supplier', verbose_name='المورد')),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان الشيت')),
                ('date', models.DateField(default=datetime.datetime(2022, 12, 4, 16, 48, 23, 676213), verbose_name='تاريخ الاضافة')),
                ('bons', models.IntegerField(blank=True, default=0, null=True, verbose_name='البونات')),
                ('quantity', models.FloatField(blank=True, default=0, null=True, verbose_name='الكميات')),
                ('quantity_discount', models.FloatField(default=0.0, verbose_name='خصم')),
                ('quantity_after_discount', models.FloatField(default=0.0, verbose_name='بعد الخصم')),
                ('quantity_diff', models.FloatField(default=0.0, verbose_name='فرق التكعيب')),
                ('total', models.FloatField(blank=True, default=0, null=True, verbose_name='حساب المورد')),
                ('overall', models.FloatField(blank=True, default=0, null=True, verbose_name='حسابي')),
                ('loads_value', models.FloatField(blank=True, default=0, null=True, verbose_name='قيمة العهد')),
                ('supplier_value', models.FloatField(blank=True, default=0, null=True, verbose_name='الصافي للمورد')),
                ('profit', models.FloatField(blank=True, default=0, null=True, verbose_name='الربح')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.supplier', verbose_name='المورد')),
            ],
        ),
        migrations.CreateModel(
            name='GeoPlacePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('old_price', models.FloatField(default=0.0, verbose_name='السعر القديم')),
                ('new_price', models.FloatField(default=0.0, verbose_name='السعر الجديد')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.geoplace', verbose_name='الموقع')),
            ],
        ),
        migrations.CreateModel(
            name='GeoPlaceMaterialPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('old_price', models.FloatField(default=0.0, verbose_name='السعر القديم')),
                ('new_price', models.FloatField(default=0.0, verbose_name='السعر الجديد')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.geoplace', verbose_name='الموقع')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('cash_amount', models.FloatField(default=0, null=True, verbose_name='القيمة النقدية')),
                ('desc', models.CharField(max_length=250, null=True, verbose_name='الوصف/السبب')),
                ('payment_date', models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.company', verbose_name='الشركة')),
                ('geo_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Engineering.geoplace', verbose_name='الموقع')),
            ],
        ),
        migrations.CreateModel(
            name='Bon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('date', models.DateField(default=datetime.datetime(2022, 12, 4, 16, 48, 23, 691838), verbose_name='التاريخ')),
                ('bon_number', models.CharField(max_length=50, verbose_name='رقم البون')),
                ('car_number', models.CharField(max_length=50, null=True, verbose_name='رقم الشاحنة')),
                ('car_owner', models.CharField(max_length=100, null=True, verbose_name='صاحب االشاحنة')),
                ('kassara', models.CharField(max_length=100, null=True, verbose_name='اسم الكسارة')),
                ('bon_quantity', models.FloatField(default=0.0, verbose_name='الكمية')),
                ('bon_quantity_discount', models.FloatField(default=0.0, verbose_name='خصم كمية')),
                ('bon_quantity_after_discount', models.FloatField(default=0.0, verbose_name='بعد الخصم')),
                ('bon_quantity_diff', models.FloatField(default=0.0, verbose_name='فرق التكعيب')),
                ('bon_price', models.FloatField(default=0.0, verbose_name='السعر')),
                ('bon_total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='الاجمالي للمورد')),
                ('material_price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='سعر الخامة')),
                ('material_total', models.FloatField(blank=True, default=0.0, null=True, verbose_name='اجمالي الخامة')),
                ('geo_price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='سعر الموقع')),
                ('bon_overall', models.FloatField(blank=True, default=0.0, null=True, verbose_name='الحساب عند الشركة')),
                ('profit', models.FloatField(blank=True, default=0.0, null=True, verbose_name='الربح من الكمية')),
                ('diff_profit', models.FloatField(blank=True, default=0.0, null=True, verbose_name='ربح فرق التكعيب')),
                ('total_profit', models.FloatField(blank=True, default=0.0, null=True, verbose_name='اجمالي الربح')),
                ('load_value', models.FloatField(default=0.0, null=True, verbose_name='العهدة')),
                ('supplier_value', models.FloatField(default=0.0, null=True, verbose_name='الصافي للمورد')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Engineering.company', verbose_name='الشركة')),
                ('geo_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.geoplace', verbose_name='الموقع')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.sheet', verbose_name='الشيت')),
            ],
        ),
    ]
