# Generated by Django 3.2.5 on 2022-10-14 02:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الشركة')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='رقم الهاتف')),
                ('active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GeoPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الموقع')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='رقم الهاتف')),
                ('price', models.FloatField(default=0.0, verbose_name='السعر')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.company', verbose_name='الشركة المسؤولة')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المورد')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='رقم الهاتف')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان الشيت')),
                ('date', models.DateField(default=datetime.datetime(2022, 10, 14, 4, 17, 10, 287407), verbose_name='تاريخ الاضافة')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.company', verbose_name='الشركة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.supplier', verbose_name='المورد')),
            ],
        ),
        migrations.CreateModel(
            name='GeoPlacePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('old_price', models.FloatField(default=0.0, verbose_name='السعر القديم')),
                ('new_price', models.FloatField(default=0.0, verbose_name='السعر الجديد')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.geoplace', verbose_name='الموقع')),
            ],
        ),
        migrations.CreateModel(
            name='Bon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('date', models.DateField(default=datetime.datetime(2022, 10, 14, 4, 17, 10, 288405), verbose_name='التاريخ')),
                ('bon_number', models.CharField(max_length=50, verbose_name='رقم البون')),
                ('car_number', models.CharField(max_length=50, verbose_name='رقم الشاحنة')),
                ('car_owner', models.CharField(max_length=50, verbose_name='صاحب االشاحنة')),
                ('bon_quantity', models.FloatField(default=0.0, verbose_name='الكمية')),
                ('bon_price', models.FloatField(default=0.0, verbose_name='السعر')),
                ('bon_total', models.FloatField(blank=True, null=True, verbose_name='الاجمالي')),
                ('geo_price', models.FloatField(blank=True, null=True, verbose_name='سعر الموقع')),
                ('profit', models.FloatField(blank=True, null=True, verbose_name='الربح')),
                ('total_profit', models.FloatField(blank=True, null=True, verbose_name='اجمالي الربح')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('geo_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.geoplace', verbose_name='الموقع')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.sheet', verbose_name='الشيت')),
            ],
        ),
    ]
