# Generated by Django 3.2.5 on 2022-10-15 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='profit',
            field=models.FloatField(blank=True, null=True, verbose_name='الربح'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 15, 17, 48, 15, 121278), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 15, 17, 48, 15, 121278), verbose_name='تاريخ الاضافة'),
        ),
    ]
