# Generated by Django 3.2.5 on 2022-10-11 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Engineering', '0002_geoplace_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPlacePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('old_price', models.FloatField(default=0.0, verbose_name='السعر القديم')),
                ('new_price', models.FloatField(default=0.0, verbose_name='السعر الجديد')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.geoplace', verbose_name='الموقع')),
            ],
        ),
    ]
