# Generated by Django 3.2.5 on 2022-10-17 05:04

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0003_auto_20221015_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الاضافة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 17, 7, 4, 25, 364527), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 17, 7, 4, 25, 364527), verbose_name='تاريخ الاضافة'),
        ),
    ]
