# Generated by Django 3.2.5 on 2022-10-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0004_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
