# Generated by Django 3.2.5 on 2022-10-18 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0005_auto_20221018_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon',
            name='bon_overall',
            field=models.FloatField(blank=True, null=True, verbose_name='المطلوب'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 0, 55, 56, 421291), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 0, 55, 56, 420291), verbose_name='تاريخ الاضافة'),
        ),
    ]
