# Generated by Django 3.2.5 on 2022-10-11 21:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Engineering', '0005_supplier_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان الشيت')),
                ('date', models.DateField(default=datetime.datetime(2022, 10, 11, 23, 12, 59, 256912), verbose_name='تاريخ الاضافة')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.company', verbose_name='الشركة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.supplier', verbose_name='المورد')),
            ],
        ),
        migrations.CreateModel(
            name='Bon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('date', models.DateField(default=datetime.datetime(2022, 10, 11, 23, 12, 59, 256912), verbose_name='التاريخ')),
                ('bon_number', models.CharField(max_length=50, verbose_name='رقم البون')),
                ('car_number', models.CharField(max_length=50, verbose_name='رقم الشاحنة')),
                ('car_owner', models.CharField(max_length=50, verbose_name='صاحب االشاحنة')),
                ('bon_quantity', models.FloatField(default=0.0, verbose_name='الكمية')),
                ('bon_price', models.FloatField(default=0.0, verbose_name='السعر')),
                ('bon_total', models.FloatField(blank=True, null=True, verbose_name='الاجمالي')),
                ('geo_price', models.FloatField(blank=True, null=True, verbose_name='سعر الموقع')),
                ('profit', models.FloatField(blank=True, null=True, verbose_name='الربح')),
                ('total_profit', models.FloatField(blank=True, null=True, verbose_name='اجمالي الربح')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('geo_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.geoplace', verbose_name='الموقع')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.sheet', verbose_name='الشيت')),
            ],
        ),
    ]
