# Generated by Django 3.2.5 on 2022-10-18 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0006_auto_20221019_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='bon_overall',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='المطلوب'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='bon_total',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='الاجمالي'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 0, 59, 14, 13481), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='geo_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='سعر الموقع'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='profit',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='الربح'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='total_profit',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='اجمالي الربح'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 0, 59, 14, 12462), verbose_name='تاريخ الاضافة'),
        ),
    ]
