# Generated by Django 3.2.5 on 2022-10-18 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0007_auto_20221019_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='bon_overall',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 1, 2, 14, 864432), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 19, 1, 2, 14, 863412), verbose_name='تاريخ الاضافة'),
        ),
    ]
