# Generated by Django 3.2.5 on 2022-11-08 09:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Engineering', '0008_auto_20221019_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 8, 11, 12, 13, 153762), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 8, 11, 12, 13, 153762), verbose_name='تاريخ الاضافة'),
        ),

        migrations.CreateModel(
            name='CompanyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('cash_amount', models.FloatField(verbose_name='القيمة النقدية')),
                ('payment_date', models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.supplier', verbose_name='الشركة')),
            ],
        ),
    ]
