# Generated by Django 3.2.5 on 2022-11-08 09:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Engineering', '0009_auto_20221108_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 8, 11, 16, 58, 663717), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='companypayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 8, 11, 16, 58, 663717), verbose_name='تاريخ الاضافة'),
        ),

    ]
