# Generated by Django 3.2.5 on 2022-11-09 13:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Engineering', '0010_auto_20221108_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypayment',
            name='desc',
            field=models.CharField(max_length=250, null=True, verbose_name='الوصف/السبب'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 15, 46, 15, 327457), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='companypayment',
            name='cash_amount',
            field=models.FloatField(default=0, null=True, verbose_name='القيمة النقدية'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 15, 46, 15, 325458), verbose_name='تاريخ الاضافة'),
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاضافة')),
                ('cash_amount', models.FloatField(default=0, null=True, verbose_name='القيمة النقدية')),
                ('desc', models.CharField(max_length=250, null=True, verbose_name='الوصف/السبب')),
                ('payment_date', models.DateField(default=datetime.date.today, null=True, verbose_name='التاريخ')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engineering.supplier', verbose_name='المورد')),
            ],
        ),
    ]
