# Generated by Django 3.2.5 on 2022-11-09 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0011_auto_20221109_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoplace',
            name='material_price',
            field=models.FloatField(default=0.0, verbose_name='سعر الخامة'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 21, 3, 7, 876233), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='geoplace',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='سعر الموقع'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 21, 3, 7, 875234), verbose_name='تاريخ الاضافة'),
        ),
    ]
