# Generated by Django 3.2.5 on 2022-11-09 19:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0013_auto_20221109_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='company',
        ),
        migrations.AddField(
            model_name='bon',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Engineering.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 21, 59, 29, 711665), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 21, 59, 29, 710666), verbose_name='تاريخ الاضافة'),
        ),
    ]
