# Generated by Django 3.2.5 on 2022-11-09 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0014_auto_20221109_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon',
            name='load_value',
            field=models.FloatField(default=0.0, verbose_name='العهدة'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 22, 19, 4, 42398), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 22, 19, 4, 41399), verbose_name='تاريخ الاضافة'),
        ),
    ]
