# Generated by Django 3.2.5 on 2022-11-09 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0016_auto_20221109_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 10, 0, 2, 59, 329822), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 10, 0, 2, 59, 328823), verbose_name='تاريخ الاضافة'),
        ),
    ]
