# Generated by Django 3.2.5 on 2022-11-10 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0019_auto_20221110_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='bons',
            field=models.IntegerField(blank=True, null=True, verbose_name='البونات'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 10, 2, 16, 24, 146418), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 10, 2, 16, 24, 145419), verbose_name='تاريخ الاضافة'),
        ),
    ]
