# Generated by Django 3.2.5 on 2022-11-10 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0020_auto_20221110_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 10, 17, 54, 21, 458678), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='bons',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='البونات'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 10, 17, 54, 21, 457678), verbose_name='تاريخ الاضافة'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='loads_value',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='قيمة العهد'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='overall',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='حسابي'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='profit',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='الربح'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='quantity',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='الكميات'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='حساب المورد'),
        ),
    ]
