# Generated by Django 3.2.5 on 2022-11-24 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0021_auto_20221110_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon',
            name='bon_quantity_after_discount',
            field=models.FloatField(default=0.0, verbose_name='بعد الخصم'),
        ),
        migrations.AddField(
            model_name='bon',
            name='bon_quantity_diff',
            field=models.FloatField(default=0.0, verbose_name='فرق التكعيب'),
        ),
        migrations.AddField(
            model_name='bon',
            name='bon_quantity_discount',
            field=models.FloatField(default=0.0, verbose_name='خصم'),
        ),
        migrations.AddField(
            model_name='bon',
            name='diff_profit',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='ربح فرق التكعيب'),
        ),
        migrations.AddField(
            model_name='bon',
            name='kassara',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم الكسارة'),
        ),
        migrations.AddField(
            model_name='bon',
            name='material_price',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='سعر الخامة'),
        ),
        migrations.AddField(
            model_name='bon',
            name='material_total',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='اجمالي الخامة'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='quantity_after_discount',
            field=models.FloatField(default=0.0, verbose_name='بعد الخصم'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='quantity_diff',
            field=models.FloatField(default=0.0, verbose_name='فرق التكعيب'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='quantity_discount',
            field=models.FloatField(default=0.0, verbose_name='خصم'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='bon_overall',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='الحساب عند الشركة'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='bon_total',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='الاجمالي للمورد'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='car_owner',
            field=models.CharField(max_length=100, null=True, verbose_name='صاحب االشاحنة'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 17, 52, 35, 304903), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='profit',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='الربح من الكمية'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 17, 52, 35, 304903), verbose_name='تاريخ الاضافة'),
        ),
    ]
