# Generated by Django 3.2.5 on 2022-11-24 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0023_auto_20221124_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon',
            name='supplier_value',
            field=models.FloatField(default=0.0, null=True, verbose_name='الصافي للمورد'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 22, 42, 23, 904309), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 22, 42, 23, 904309), verbose_name='تاريخ الاضافة'),
        ),
    ]
