# Generated by Django 3.2.5 on 2022-11-24 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0024_auto_20221124_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='supplier_value',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='الصافي للمورد'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 22, 51, 45, 458114), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 22, 51, 45, 458114), verbose_name='تاريخ الاضافة'),
        ),
    ]
