# Generated by Django 3.2.5 on 2022-11-26 23:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Engineering', '0025_auto_20221124_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypayment',
            name='geo_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Engineering.geoplace', verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 27, 1, 29, 16, 663218), verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 27, 1, 29, 16, 663218), verbose_name='تاريخ الاضافة'),
        ),
    ]
