# Generated by Django 3.2.5 on 2022-10-03 00:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='اسم العامل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='صورة العامل')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='رقم الموبيل')),
                ('worker_type', models.IntegerField(blank=True, choices=[(5, 'عامل يوميه'), (6, 'عامل انتاج')], null=True, verbose_name='نوع العامل')),
                ('day_cost', models.FloatField(blank=True, default=0, null=True, verbose_name='التكلفة (*حساب اليومية في حالة عامل اليومية *حساب القطعة في حالة عامل الانتاج)')),
                ('deleted', models.BooleanField(default=False, verbose_name='حذف')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2022, 10, 3, 0, 4, 59, 63663, tzinfo=utc), verbose_name='تاريخ الاستلام')),
                ('day', models.CharField(max_length=30, verbose_name='اليوم')),
                ('quantity', models.FloatField(default=0, verbose_name='الكمية بالقطعة')),
                ('price', models.FloatField(default=0, verbose_name='فئة السعر')),
                ('total', models.FloatField(default=0, verbose_name='الإجمالي')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workers.worker', verbose_name='العامل')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2022, 10, 3, 0, 4, 59, 62664, tzinfo=utc), verbose_name='تاريخ السحب')),
                ('price', models.FloatField(verbose_name='المبلغ')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workers.worker', verbose_name=' العامل')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2022, 10, 3, 0, 4, 59, 61662, tzinfo=utc), verbose_name='تاريخ الحضور')),
                ('day', models.CharField(max_length=30, verbose_name='اليوم')),
                ('hour_count', models.IntegerField(blank=True, choices=[(1, '6'), (2, '8'), (3, '12'), (4, '18')], null=True, verbose_name='عدد الساعات')),
                ('attend', models.BooleanField(default=0, verbose_name='حضر')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المسئول')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workers.worker', verbose_name='العامل')),
            ],
        ),
    ]
