# Generated by Django 3.2.5 on 2022-10-12 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0003_auto_20221005_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerattendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 20, 43, 39, 324098, tzinfo=utc), verbose_name='تاريخ الحضور'),
        ),
        migrations.AlterField(
            model_name='workerpayment',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 20, 43, 39, 324098, tzinfo=utc), verbose_name='تاريخ السحب'),
        ),
        migrations.AlterField(
            model_name='workerproduction',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 20, 43, 39, 324098, tzinfo=utc), verbose_name='تاريخ الاستلام'),
        ),
    ]
