# Generated by Django 3.2.5 on 2022-10-03 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 2, 26, 33, 689779), verbose_name='التاريخ'),
        ),
    ]
