# Generated by Django 3.2.5 on 2022-10-05 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 5, 17, 5, 35, 236317), verbose_name='التاريخ'),
        ),
    ]
