# Generated by Django 3.2.5 on 2022-10-12 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_sellerpayments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 12, 22, 43, 39, 308473), verbose_name='التاريخ'),
        ),
    ]
